// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

uint256 constant RECEIVER_CONSTRAINTS_NONE = 0;
uint256 constant RECEIVER_CONSTRAINTS_NO_CODE = 1;
uint256 constant RECEIVER_CONSTRAINTS_EOA = 2;
uint256 constant RECEIVER_CONSTRAINTS_SBT = 3;

uint256 constant CALLER_CONSTRAINTS_NONE = 0;
uint256 constant CALLER_CONSTRAINTS_OPERATOR_BLACKLIST_ENABLE_OTC = 1;
uint256 constant CALLER_CONSTRAINTS_OPERATOR_WHITELIST_ENABLE_OTC = 2;
uint256 constant CALLER_CONSTRAINTS_OPERATOR_WHITELIST_DISABLE_OTC = 3;
uint256 constant CALLER_CONSTRAINTS_SBT = 4;

uint8 constant TRANSFER_SECURITY_LEVEL_RECOMMENDED = 0;
uint8 constant TRANSFER_SECURITY_LEVEL_ONE = 1;
uint8 constant TRANSFER_SECURITY_LEVEL_TWO = 2;
uint8 constant TRANSFER_SECURITY_LEVEL_THREE = 3;
uint8 constant TRANSFER_SECURITY_LEVEL_FOUR = 4;
uint8 constant TRANSFER_SECURITY_LEVEL_FIVE = 5;
uint8 constant TRANSFER_SECURITY_LEVEL_SIX = 6;
uint8 constant TRANSFER_SECURITY_LEVEL_SEVEN = 7;
uint8 constant TRANSFER_SECURITY_LEVEL_EIGHT = 8;
uint8 constant TRANSFER_SECURITY_LEVEL_NINE = 9;

uint8 constant LIST_TYPE_BLACKLIST = 0;
uint8 constant LIST_TYPE_WHITELIST = 1;
uint8 constant LIST_TYPE_AUTHORIZERS = 2;

bytes4 constant SELECTOR_NO_ERROR = bytes4(0x00000000);